[package]
name = "templar"
version = "0.1.1"
authors = ["Michael Shaw <michaeljshaw@gmail.com>", "Rob Saunders <rob@wearebrandnew.com>"]

[dependencies.nom]
version = "3.2"
features = ["std", "stream", "verbose-errors"]
